/**
 * Generates the secrets a local .env needs, and prints them to stdout.
 *
 *   bun run scripts/generate-keys.ts >> .env
 *
 * These are DEVELOPMENT values. Production secrets are generated once, stored in the
 * deployment platform's secret store and the team password manager, and never pass
 * through a terminal that has scrollback.
 */
import { generateKeyPairSync, randomBytes } from 'node:crypto';

const secret = (bytes = 48): string => randomBytes(bytes).toString('base64url');

// Ed25519: the ticket QR signature. The scanner ships ONLY the public key, so a stolen
// scanner cannot mint tickets.
const { publicKey, privateKey } = generateKeyPairSync('ed25519');

const lines = [
  '',
  '# --- generated by scripts/generate-keys.ts — DEVELOPMENT ONLY ---',
  `JWT_ACCESS_SECRET=${secret()}`,
  `JWT_REFRESH_SECRET=${secret()}`,
  `TICKET_SIGNING_PRIVATE_KEY=${privateKey.export({ type: 'pkcs8', format: 'der' }).toString('base64')}`,
  `TICKET_SIGNING_PUBLIC_KEY=${publicKey.export({ type: 'spki', format: 'der' }).toString('base64')}`,
  'TICKET_SIGNING_KEY_VERSION=1',
  `STORAGE_ACCESS_KEY_ID=eventis`,
  `STORAGE_SECRET_ACCESS_KEY=eventis-dev-secret`,
];

process.stdout.write(lines.join('\n') + '\n');
